import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";
import { existsSync, readFileSync } from "fs";
import { sassPlugin } from "esbuild-sass-plugin";

if (existsSync(".env")) dotenv.config();

const packageJson = JSON.parse(readFileSync("package.json", "utf8"));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		"process.env.BETA_SERVER": JSON.stringify(
			process.env.BETA_SERVER || "vertical-tabs-prod.oxdc.dev"
		),
		"process.env.USER_AGENT_VERSION": JSON.stringify(
			process.env.USER_AGENT_VERSION || packageJson.version
		),
	},
	entryPoints: ["src/styles.scss", "src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	minify: prod,
	plugins: [sassPlugin()],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
